### ISSUE TITLE
Light intensity not working on 3DS

### ISSUE THREAD

**Issue by AGO061** [mholtkamp/octave#21]
The light intensity slider works on PC but it does not work when packaging for the 3DS.

This applies both for `Directional Light` and `Point Light` nodes.

**Comment by mholtkamp** [comment]
Thanks for reporting this! Does the intensity at least decrease if you set it below 1.0? Going above 1.0 doesn't do anything on 3DS right now, but I think I might be able to fix it, or at least enable you to go up to an intensity of 4.0.

**Comment by mholtkamp** [comment]
Quick update on this: I pushed a commit that enables light intensity up to 4.0 on 3DS. I tested it with a point light, but it should work on directional lights too. GameCube/Wii are still restricted to the 0 - 1 range.

**Comment by AGO061** [comment]
Thanks i'll check it out asap, keep up the great work, i love the engine :)

**Comment by AGO061** [comment]
Yup, it works from 0.0 to 4.0
